### ISSUE TITLE
consider enabling --visit-external by default

### ISSUE THREAD

**Issue by matkoniecz** [tomlinsonk/site-graph#11]
At least for me it would be quite confusing to have error checked and shown as broken internal links and the same not happening with external links

At least I [was confused](https://github.com/matkoniecz/website-checklist/commit/00ac28319bd4cf48b1348530c8db5d36a39366d2). Can it be enabled by default?

**Comment by tomlinsonk** [comment]
Sure! I just did this for efficiency when I has testing on lots of sites.

Edit: It looks like many sites don't respond well to requests from python's `requests` (lots of 403 errors from common sites, even for valid webpages, I think because they don't want to be crawled/DDOS'd). If anyone knows a workaround for this, let me know. In the meantime, I think it's best not to enable `--visit-external` by default due to the high false positive rate

**Comment by matkoniecz** [comment]
passing user agent of a browser may work
