### ISSUE TITLE
consider changing color for error

### ISSUE THREAD

**Issue by matkoniecz** [tomlinsonk/site-graph#5]
> red nodes are external pages, and yellow nodes are pages with errors

Maybe it would make more sense to use black/red/eyesore red/magenta for errors?

Red for errors is quite typical, maybe color like

![screen04](https://user-images.githubusercontent.com/899988/128180347-835c449b-bfae-49f1-95d3-be16b83c4d77.png)

would be even better?

(would be happy to make PR if that would be accepted and #3 is resoved)

**Comment by tomlinsonk** [comment]
Feel free to make a PR--I don't have strong opinions about the colors, as long as they're easy to distinguish

**Comment by matkoniecz** [comment]
Is https://www.cs.cornell.edu/~kt/post/site-graph/ also in a public repo? (then potential PR changing colours would be accompanied by update also to that - or would you prefer to keep original colours there?)

Which site was used to generate https://github.com/tomlinsonk/site-graph/blob/master/example.png example? It also would be nice to update it. It seems to not be your own website (and a good thing, given bitrotten links there!).

It is one of 

> Here are some screenshots of other websites I’ve mapped. 

but seems unlisted which site is depicted here.

**Comment by tomlinsonk** [comment]
i'm fine with changing the colors on my site--I'll just handle that manually when I next update it. 

The websites I mapped belong to a few different computer science professors at various universities--I intentionally didn't name them for anonymity (they might not want attention called to how many broken links they have 😂 but it makes for a nice example). If you find a site that has a nice graph, i'm fine with changing the example. Otherwise, I'm happy to rerun the updated script on the same website once we have new colors
